### ISSUE TITLE
Error when running process_Ilastik_run_this

### ISSUE THREAD

**Issue by DCoss1995** [MoritzNegwer/FriendlyClearMap-scripts#2]
Hi. I tried to run process_Ilastik_run_thi.py file, but this is what I got in return.

![img errore](https://github.com/MoritzNegwer/FriendlyClearMap-scripts/assets/83833508/9e2cc7a3-1409-4933-8a95-8a99a22b27b5)

I have one folder "Sample" where there are:
- the 1643 images from the example.
- the  process_Ilastik_run_thi.py file.
- the atlas folder.

**Comment by MoritzNegwer** [comment]
Hi @DCoss1995 , thanks for your interest! 

For posterity: It looks like the script could not find the expected data in the input folder (`/CloudMap/Data/` inside the docker,  `C:\Users\Wetlab\Desktop\Sample` on your PC). I assume that e.g. there was a subfolder in there, or the zip with the validation data hadn't been unpacked. Glad that you seem to have solved it. 

If you have any further questions, please do not hesitate to get in contact.

**Comment by DCoss1995** [comment]
Hi @MoritzNegwer. Actually it was a gross mistake of mine because I typed the filename wrong. Thank you.
